Repository PostHog/posthog.com, pull requests merged in 2021-08, with the labels that each got.

#1708 Brief overview update of DevRel @ PostHog
  contents/handbook/growth/developer-relations/index.mdx
  contents/handbook/growth/marketing/developer-relations.mdx
  contents/images/handbook/devrel-intersection.png
  src/sidebars/sidebars.json
Labels: culture/ops docs

#1714 Fix colors in light and dark mode
  src/components/Layout/DarkMode.scss
  src/components/Layout/Layout.scss
Labels: high-priority

#1656 Leo Anthias Interview
  .codespellignore
  contents/blog/leo-anthias-interview.md
  contents/images/blog/leo-anthias.png
Labels: community, marketing

#1741 Running content at posthog
  contents/blog/running-content-at-posthog.md
  contents/images/blog/running-content.png
Labels: marketing

#1770 Add DocSearch filter
  src/components/DocsSearch/index.js
Labels: high-priority

#1737 Add cloud overview docs
  contents/docs/cloud/index.mdx
  src/sidebars/sidebars.json
Labels: technical docs

#1796 Blog Post: How We Got Our First 10 Paying Customers
  contents/blog/first-10-paying-customers.md
Labels: marketing

#1759 ClickHouse Announcement
  contents/blog/clickhouse-announcement.md
  contents/images/blog/clickhouse-announcement.png
Labels: marketing

#1764 Cookieless Analytics
  contents/blog/cookieless-analytics.md
  contents/images/blog/cookieless-analytics.png
Labels: marketing

#1842 Next.js integration
  contents/docs/integrate/third-party/next-js.md
  src/sidebars/sidebars.json
Labels: technical docs, extra merch

#1760 Product at PostHog - Blog post
  contents/authors.md
  contents/blog/product-at-posthog.md
  contents/images/blog/product-at-posthog.png
Labels: marketing, product

#1856 Update leo-anthias-interview.md
  contents/blog/leo-anthias-interview.md
Labels: marketing
