Repository PostHog/posthog.com, pull requests merged in 2022-02, with the labels that each got.

#2846 Blog: Best GDPR Compliant Analytics Tools
  contents/blog/best-gdpr-compliant-analytics-tools.md
  contents/blog/best-open-source-analytics-tools.md
  contents/images/blog/gdpr-compliant-analytics/goaccess-gdpr-compliant.png
  contents/images/blog/gdpr-compliant-analytics/posthog-gdpr-compliant.png
Labels: marketing

#2856 HostHog landing page
  contents/docs/contribute/contribute-to-website.md
  contents/hosthog/london.mdx
  contents/images/hosthog/london/featured.png
  contents/images/hosthog/london/hosthog_london.png
  contents/images/hosthog/london/og.png
  contents/images/hosthog/london/speakers/anca.png
  contents/images/hosthog/london/speakers/james.png
  contents/images/hosthog/london/speakers/marcus.png
  gatsby/createPages.js
  src/components/CommunityQuestions/EmailSubmitted.js
  src/components/Section/index.tsx
  src/components/Subscribe/hog-the-builder.png
  src/components/Subscribe/index.js
  src/mdxGlobalComponents.js
  src/templates/HostHog.js
Labels: marketing

#2648 Feedback loop blogpost
  contents/blog/feedback-loops.md
  netlify.toml
  src/data/authors.json
  static/images/authors/neil-posthog.png
Labels: marketing

#2921 Change title
  contents/docs/self-host/deploy/troubleshooting.md
Labels: merge after check

#2914 Blog: Send love to open source campaign
  contents/blog/send-love-to-open-source.md
  contents/images/blog/send-love-to-open-source.png
Labels: marketing

#2851 Update to reflect new categories
  contents/handbook/growth/marketing/blog.md
Labels: culture/ops docs

#2793 Missing recordings blog post
  contents/blog/missing-recordings.md
  netlify.toml
Labels: marketing

#2948 Tutorial: How to filter out internal users
  contents/images/tutorials/banners/internal-users-filter.png
  contents/images/tutorials/internal-users/step1.png
  contents/images/tutorials/internal-users/step2.png
  contents/images/tutorials/internal-users/step3.png
  contents/tutorials/filter-internal-users.md
  contents/tutorials/how-to-segment-users.md
Labels: marketing

#2969 Blog post FAQ for HostHogs.
  contents/blog/hosthog-blog.md
  contents/images/blog/hosthog-banner.png
Labels: marketing

#2994 Adding 'Privacy' section to Docs covering GDPR, CCPA and HIPAA
  contents/docs/privacy/ccpa-compliance.md
  contents/docs/privacy/gdpr-compliance.md
  contents/docs/privacy/hipaa-compliance.md
  contents/docs/privacy/index.md
  netlify.toml
  src/sidebars/sidebars.json
Labels: technical docs

#2875 Blog: Is Google Analytics HIPAA compliant?
  contents/blog/is-google-analytics-hipaa-compliant.md
  netlify.toml
Labels: marketing, SEO

#2979 Blog: A simple guide to personal data and PII
  contents/blog/what-is-personal-data-pii.md
Labels: marketing

#3024 Add figma access to checklist
  contents/handbook/people/onboarding.md
Labels: culture/ops docs

#3032 Hightouch integration announcement
  contents/blog/hightouch-posthog-reverse-etl-integration.md
Labels: marketing
