Repository PostHog/posthog.com, pull requests merged in 2022-10, with the labels that each got.

#4046 Y Combinator x PostHog Case Study
  contents/customers/vendasta.md
  contents/customers/ycombinator.md
  contents/images/customers/ycombinator/featured.svg
  contents/images/customers/ycombinator/yc_logo.png
  contents/images/customers/ycombinator/yc_logo_b.png
  contents/images/customers/ycombinator/ycombinator-analytics.png
  src/components/Customers/index.js
  src/components/MainNav/Submenus/Product/ycombinator.svg
  src/templates/Customer.js
  static/images/customers/cat.jpeg
Labels: marketing

#4158 Denote paid/premium features in the manual
  contents/images/features/cohorts/lifecycle.png
  contents/manual/actions.mdx
  contents/manual/annotations.mdx
  contents/manual/application-settings.md
  contents/manual/cohorts.mdx
  contents/manual/correlation.mdx
  contents/manual/dashboards.mdx
  contents/manual/data-management.mdx
  contents/manual/events.mdx
  contents/manual/experimentation.mdx
  contents/manual/feature-flags.mdx
  contents/manual/funnels.mdx
  contents/manual/group-analytics.mdx
  contents/manual/insights.md
  contents/manual/lifecycle.mdx
  contents/manual/notifications-and-alerts.mdx
  contents/manual/organizations-and-projects.mdx
  contents/manual/paths.mdx
  contents/manual/persons.mdx
  contents/manual/recordings.mdx
  contents/manual/retention.mdx
  contents/manual/sessions.md
  contents/manual/sso.mdx
  contents/manual/stickiness.mdx
  contents/manual/toolbar.mdx
  contents/manual/trends.mdx
  contents/manual/utm-segmentation.mdx
  src/components/Careers/WhyWereHere/AnchorScrollNavbarTop/index.tsx
  src/components/FeatureAvailability/index.tsx
  src/components/PostLayout/index.tsx
  src/pages/using-posthog.tsx
  src/templates/Handbook.tsx
  yarn.lock
Labels: enhancement, user-guides

#4346 EU Cloud - Early announce banner
  src/components/StarUsBanner/index.js
Labels: marketing

#4341 New tutorial banners
  contents/images/tutorials/banners/cookieless-tracking.png
  contents/images/tutorials/banners/cookies-tracking.png
  contents/images/tutorials/banners/patterns-app-tutorial.png
  contents/images/tutorials/banners/patterns-tutorial.png
  contents/tutorials/cookieless-tracking.md
  contents/tutorials/how-to-connect-patterns-and-posthog.md
Labels: marketing

#4427 Puts EU Migration in Migration Docs
  src/sidebars/sidebars.json
Labels: marketing

#4435 Soften 'GDPR compliant' claim on EU landing page
  src/components/EU/index.tsx
Labels: marketing

#4438 Delete eu-cloud.js
  netlify.toml
  src/pages/signup/eu-cloud.js
Labels: marketing

#4425 The PostHog Glossary
  contents/images/logos/gloss_hog.png
  contents/manual/glossary.mdx
  src/sidebars/sidebars.json
Labels: marketing

#4415 Creates Hogmail blog post
  contents/blog/hogmail-14.md
  contents/images/blog/hogmail.png
Labels: content

#4478 Add index to glossary
  contents/manual/glossary.mdx
Labels: marketing

#4433 blog - 'how we made something people want'
  contents/blog/making-something-people-want.md
Labels: content

#4463 New blog: GA4 alternatives
  contents/blog/best-gdpr-compliant-analytics-tools.md
  contents/blog/best-open-source-analytics-tools.md
  contents/blog/ga4-alternatives.md
  contents/blog/is-google-analytics-illegal-microsite.md
  contents/blog/track-your-website-with-posthog.md
  contents/images/blog/ga4-alternatives/piwik-pro.png
  contents/images/blog/ga4-alternatives/telemetrydeck.png
Labels: content

#3969 Open source seo article
  contents/blog/open-source-stack-for-engineers.md
  contents/images/blog/open-source-engineers/clickhouse-open-source.png
  contents/images/blog/open-source-engineers/metabase-open-source.png
  contents/images/blog/open-source-engineers/n8n-open-source.png
  contents/images/blog/open-source-engineers/netdata-open-source.png
  contents/images/blog/open-source-engineers/nocodb-open-source.png
  contents/images/blog/open-source-engineers/rudderstack-open-source.png
  netlify.toml
  src/components/Careers/OpenRoles/index.tsx
  src/mdxGlobalComponents.js
Labels: marketing

#4524 Laudspeaker app listing
  contents/apps/laudspeaker-connector/index.mdx
  contents/apps/thumbnails/laudspeaker-connector.png
  contents/docs/apps/laudspeaker-connector.md
Labels: marketing

#4225 New hogs, new banners for press page
  contents/images/media/social-media-headers/hogs/builder_hog.png
  contents/images/media/social-media-headers/hogs/detective_hog.png
  contents/images/media/social-media-headers/hogs/professor_hog.png
  contents/media.mdx
Labels: marketing

#4546 HogMail 15
  contents/blog/hogmail-15.md
Labels: content

#4521 Create filter out app listing
  contents/apps/filter-out/index.mdx
  contents/apps/thumbnails/filter-out.png
  contents/docs/apps/filter-out.md
Labels: marketing
