Repository PostHog/posthog.com, pull requests merged in 2022-05, with the labels that each got.

#3380 Feature Flags comparison chart for product page
  contents/product/feature-flags.mdx
Labels: marketing

#3374 Three new tutorials - How to use PostHog with Notion, Sentry & Discord
  contents/images/tutorials/banners/discord-tutorial-banner.png
  contents/images/tutorials/banners/notion-tutorial-banner.png
  contents/images/tutorials/banners/sentry-tutorial-banner.png
  contents/images/tutorials/discord/discord-create-action.png
  contents/images/tutorials/discord/discord-name-action.png
  contents/images/tutorials/notion/create-integration.png
  contents/images/tutorials/notion/notion-test-trigger.png
  contents/images/tutorials/sentry/sentry_retention.png
  contents/images/tutorials/sentry/trend-error-sentry.png
  contents/images/tutorials/sentry/trend-rage-error.png
  contents/tutorials/how-to-connect-discord-to-posthog-with-zapier.md
  contents/tutorials/how-to-connect-posthog-and-notion-with-zapier.md
  contents/tutorials/sentry-plugin-tutorial.md
Labels: marketing

#3396 Heatmaps comparison
  contents/product/feature-flags.mdx
  contents/product/heatmaps.mdx
  contents/product/session-recording.mdx
Labels: marketing

#3397 add restack content to marketplace
  contents/marketplace/index.md
  contents/marketplace/restack.md
  static/images/marketplace/restack.png
Labels: marketing

#3419 Overhaul the /Media page with correct branding, new content
  contents/images/media/social-media-headers/banners/linkedin_banner.jpeg
  contents/images/media/social-media-headers/banners/twitter_banner.jpeg
  contents/images/media/social-media-headers/hogs/builder_hog.png
  contents/images/media/social-media-headers/hogs/detective_hog.png
  contents/images/media/social-media-headers/hogs/professor_hog.png
  contents/images/media/social-media-headers/linkedin/build-better-products-blue.png
  contents/images/media/social-media-headers/linkedin/build-better-products-orange.png
  contents/images/media/social-media-headers/linkedin/build-better-products-red.png
  contents/images/media/social-media-headers/linkedin/build-better-products-tan.png
  contents/images/media/social-media-headers/linkedin/hog-laptop.png
  contents/images/media/social-media-headers/linkedin/two-hogs.png
  contents/images/media/social-media-headers/twitter/posthog-dark-hedgehog-1.png
  contents/images/media/social-media-headers/twitter/posthog-dark-hedgehog-2.png
  contents/images/media/social-media-headers/twitter/posthog-plain-hedgehog.png
  contents/images/media/social-media-headers/twitter/posthog-ross-chandler-pivot.png
  contents/images/media/social-media-headers/twitter/posthog-spiderman-meme.png
  contents/media.mdx
  src/components/Footer/Footer.tsx
Labels: marketing

#3415 PostHog / Restack announcement
  contents/blog/posthog-restack-announcement.md
Labels: marketing

#3427 Adding /Marketplace to the self-host disclaimer
  contents/docs/self-host/deploy/other.mdx
  contents/docs/self-host/deploy/snippets/disclaimer.mdx
  contents/docs/self-host/index.md
Labels: marketing

#3428 Migrate from amplitude
  contents/docs/self-host/migrate/migrate-from-amplitude.mdx
  src/sidebars/sidebars.json
Labels: marketing

#3404 PostHog vs Amplitude blog article
  contents/blog/best-gdpr-compliant-analytics-tools.md
  contents/blog/best-hipaa-compliant-analytics-tools.md
  contents/blog/best-open-source-analytics-tools.md
  contents/blog/posthog-vs-amplitude.md
  contents/customers/mention-me.mdx
  contents/customers/saga.mdx
  contents/images/blog/posthog-vs-amplitude/amplitude-screenshot.png
  contents/images/blog/posthog-vs-amplitude/posthog-vs-amplitude.jpeg
  netlify.toml
Labels: marketing, SEO, content

#3439 Swapping products for tools in /product hero
  src/components/ProductPage/Hero.js
Labels: marketing

#3434 Fixing app icons
  contents/apps/github-release-tracker/index.mdx
  contents/apps/github-star-sync/index.mdx
  contents/apps/gitlab-release-tracker/index.mdx
  contents/apps/redshift-export/index.mdx
  contents/apps/thumbnails/automatic-cohort-creator.png
  contents/apps/thumbnails/bitbucket-release-tracker.png
  contents/apps/thumbnails/braze.png
  contents/apps/thumbnails/currency-normalization.png
  contents/apps/thumbnails/customerio-connector.png
  contents/apps/thumbnails/databricks.png
  contents/apps/thumbnails/email-scoring.png
  contents/apps/thumbnails/event-sequence-timer-plugin.png
  contents/apps/thumbnails/first-time-event-tracker.png
  contents/apps/thumbnails/gcs-export.png
  contents/apps/thumbnails/github-release-tracker.png
  contents/apps/thumbnails/github-star-sync.png
  contents/apps/thumbnails/github.png
  contents/apps/thumbnails/gitlab-release-tracker.png
  contents/apps/thumbnails/gitlab.png
  contents/apps/thumbnails/heartbeat.png
  contents/apps/thumbnails/ingestion-alert.png
  contents/apps/thumbnails/migrator-3000.png
  contents/apps/thumbnails/orbit-stats-sync.png
  contents/apps/thumbnails/postgresql-export.png
  contents/apps/thumbnails/property-filter.png
  contents/apps/thumbnails/property-flattener.png
  contents/apps/thumbnails/rudderstack-export.png
  contents/apps/thumbnails/schema-enforcer.png
  contents/apps/thumbnails/sendgrid-connector.png
  contents/apps/thumbnails/taxonomy-standardizer.png
  contents/apps/thumbnails/timestamp-parser.png
  contents/apps/thumbnails/twitter-followers.png
  contents/apps/thumbnails/user-agent-enhancer.png
Labels: marketing

#3398 Add comparison chart to Trends product page
  contents/product/trends.mdx
Labels: marketing

#3450 New funnel comparison
  contents/product/funnels.mdx
Labels: marketing

#3472 New blog: Best open source AB testing tools
  contents/blog/best-open-source-ab-testing-tools.md
  contents/blog/best-open-source-analytics-tools.md
  contents/blog/best-open-source-session-replay-tools.md
  contents/blog/experiments.md
  contents/blog/the-posthog-array-1-33-0.md
  contents/images/blog/open-source-testing-tools/growthbook.png
  contents/images/blog/open-source-testing-tools/img1_PostHog.png
  contents/images/blog/open-source-testing-tools/img2_Unleash.png
  contents/images/blog/open-source-testing-tools/img3_Mojito.png
  contents/images/blog/open-source-testing-tools/img4_Flagsmith.png
Labels: content

#3496 Correcting error in feature flag comparison
  contents/product/feature-flags.mdx
Labels: marketing

#3489 Paths comparison chart
  contents/product/user-paths.mdx
Labels: marketing

#3495 Move Reciprocal story to blog
  contents/blog/why-i-ditched-google-analytics-for-posthog.md
  contents/customers/vendasta.md
  netlify.toml
  src/components/Customers/index.js
  src/data/authors.json
Labels: marketing

#3470 Array 1.36 Blog Announcement
  contents/blog/the-posthog-array-1-36-0.mdx
  contents/images/blog/array/1-36-0-and-or-filtering.png
  contents/images/blog/array/1-36-0-data-colors.png
  contents/images/blog/array/1-36-0-insight-on-multiple-dashboards.png
  contents/images/blog/array/1-36-0-multi-point-persons-modal.gif
  contents/images/blog/array/1-36-0-new-funnel-viz-dashboard.png
  contents/images/blog/array/1-36-0-new-funnel-viz.png
  contents/images/blog/array/1-36-0-preflight.png
  contents/images/blog/array/1-36-0-timezone.png
  contents/images/blog/array/1-36-0-universal-search.png
  netlify.toml
Labels: marketing
