Repository PostHog/posthog.com, pull requests merged in 2022-04, with the labels that each got.

#3270 Replace Ben White quote with new one
  src/components/Home/Quote.js
  src/images/nicolas_grenie.png
Labels: marketing

#3254 Update API docs for personal API key creation
  contents/docs/api/index.mdx
Labels: technical docs

#3286 Careers page image updates + speculative email
  src/components/Careers/OpenRoles/index.tsx
  src/components/Careers/WhyWereHere/images/this-hog-ships-too.png
  src/components/Careers/WhyWereHere/images/this-hog-ships.png
  src/components/Careers/WhyWereHere/images/this_hog_ships.png
  src/components/Careers/WhyWereHere/index.tsx
Labels: website

#3278 Open source session replay / Hotjar alternatives blog
  contents/blog/best-open-source-session-replay-tools.md
  contents/images/blog/open-source-hotjar-alternatives/Matomo-session-recording.png
  contents/images/blog/open-source-hotjar-alternatives/img1_PostHog.png
  contents/images/blog/open-source-hotjar-alternatives/img2_OpenReplay.png
  contents/images/blog/open-source-hotjar-alternatives/img3_UXWizz.png
  contents/images/blog/open-source-hotjar-alternatives/img4_UXlens.png
  contents/images/blog/open-source-hotjar-alternatives/img5_Matomo.png
  contents/images/blog/open-source-hotjar-alternatives/img6_SessionStack.png
  netlify.toml
Labels: SEO

#3318 Rebuilt the newsletter sign-up page
  contents/images/docs/newsletter/hogmails.png
  contents/newsletter.md
  src/components/NewsletterForm/index.tsx
Labels: marketing

#3301 Updating 'Analyzing your conversion with Funnels' tutorial
  contents/images/tutorials/funnels/continent-breakdown.png
  contents/images/tutorials/funnels/correlated-events.png
  contents/images/tutorials/funnels/experiment-result.png
  contents/images/tutorials/funnels/funnel-preview.png
  contents/images/tutorials/funnels/funnel-with-deploy-option.png
  contents/images/tutorials/funnels/insight-page.png
  contents/images/tutorials/funnels/simple-left-right.png
  contents/images/tutorials/funnels/top-to-bottom-funnel.png
  contents/tutorials/funnels.md
Labels: content

#3319 Update Lost-Hog
  src/images/lost-hog.png
Labels: marketing

#3353 A big old update to the open source analytics article
  contents/blog/best-open-source-analytics-tools.md
  contents/images/blog/open-source-analytics-tools/openreplay.png
Labels: SEO, content

#3344 1.35.0 array blog post
  contents/blog/the-posthog-array-1-35-0.md
  contents/images/blog/array/1_35_0_avo.png
  contents/images/blog/array/1_35_0_map.png
Labels: marketing

#3346 New Array CTA for blog
  contents/blog/the-posthog-array-1-0-10.md
  contents/blog/the-posthog-array-1-0-11.md
  contents/blog/the-posthog-array-1-0-8.mdx
  contents/blog/the-posthog-array-1-0-9.md
  contents/blog/the-posthog-array-1-1-0.md
  contents/blog/the-posthog-array-1-10-0.md
  contents/blog/the-posthog-array-1-11-0.md
  contents/blog/the-posthog-array-1-12-0.md
  contents/blog/the-posthog-array-1-13-0.md
  contents/blog/the-posthog-array-1-14-0.md
  contents/blog/the-posthog-array-1-15-0.md
  contents/blog/the-posthog-array-1-16-0.md
  contents/blog/the-posthog-array-1-17-0.md
  contents/blog/the-posthog-array-1-18-0.md
  contents/blog/the-posthog-array-1-19-0.md
  contents/blog/the-posthog-array-1-2-0.md
  contents/blog/the-posthog-array-1-20-0.md
  contents/blog/the-posthog-array-1-21-0.mdx
  contents/blog/the-posthog-array-1-22-0.mdx
  contents/blog/the-posthog-array-1-23-0.mdx
  contents/blog/the-posthog-array-1-24-0.mdx
  contents/blog/the-posthog-array-1-25-0.mdx
  contents/blog/the-posthog-array-1-26-0.md
  contents/blog/the-posthog-array-1-27-0.md
  contents/blog/the-posthog-array-1-3-0.md
  contents/blog/the-posthog-array-1-4-0.md
  contents/blog/the-posthog-array-1-5-0.md
  contents/blog/the-posthog-array-1-6-0.md
  contents/blog/the-posthog-array-1-7-0.md
  contents/blog/the-posthog-array-1-8-0.md
  contents/blog/the-posthog-array-1-9-0.md
  contents/blog/the-posthog-array-1.md
  src/components/ArrayCTA/index.tsx
Labels: marketing

#3343 Comparison session recordings
  contents/product/session-recording.mdx
  safelist.txt
  src/components/ArrayCTA/index.tsx
  src/components/Layout/Layout.scss
  tailwind.config.js
Labels: marketing, website

#3375 Adding CTAs for Case Studies
  src/templates/Customer.js
Labels: marketing

#3378 Creating documentation guidelines for plugins
  contents/docs/plugins/build/index.md
  contents/docs/plugins/build/tutorial.md
  contents/docs/plugins/index.md
Labels: technical docs, marketing

#3321 Updating the email documentation
  contents/handbook/engineering/release-new-version.md
  contents/handbook/growth/marketing/newsletter.md
Labels: marketing
